Fix message formatting for long truncated UTF8 strings
CuyZ/Valinor pull request #366
Opened 2023-03-28 09:52 UTC by danog

I'm also passing the intl error message to the exception to simplify debugging.

2023-04-06 10:05 UTC, romm requested changes
Thanks for the PR! Since I think this is not a common usecase, and that probably a lot of PHP apps are installed with the `mbstring` extension anyway, we'll use the `mb_strcut` function only when it is available.

2023-04-07 11:08 UTC, danog commented on composer.json
> +        "symfony/polyfill-mbstring": "^1.27"
Reimplemented mb_strcut in pure PHP, instead :)

2023-04-17 12:27 UTC, danog commented
Ping @romm? :)

2023-04-20 14:01 UTC, romm commented
Hi @danog, sorry for the delay I've been quite busy lately.

I'm not against importing a polyfill in the library, but it would need unit tests. Have you been using parts of code from somewhere else?

Could you move the implementation in another class (a static method will be enough), and add unit tests? We'd need 100% Mutation Score Indicator on this (you can use `composer mutation` to check that).

Thanks for your work!

2023-04-23 15:06 UTC, danog commented
Nah, wrote this myself just for this PR, that's OK, I imagined I'd need full mutation coverage, will do!

2023-05-05 11:55 UTC, danog commented
@romm Should be good!

2023-06-06 15:02 UTC, danog commented
Added you as a collaborator :)

2023-06-06 16:09 UTC, merged

2023-06-06 16:10 UTC, romm commented
Thank you @danog, that was a long run but we made it! 😁

2023-06-06 21:23 UTC, danog commented
Yay! :D 
Now for the general refactoring PR ;)