Strengthen datetime mapping tests
CuyZ/Valinor pull request #84
Opened 2022-03-02 20:01 UTC by Lucian-Olariu

Addresses https://github.com/CuyZ/Valinor/issues/44

2022-03-02 20:05 UTC, Ocramius requested changes

2022-03-02 20:05 UTC, Ocramius commented on tests/Integration/Mapping/Object/DateTimeMappingTest.php
> +use function mt_rand;
`mt_rand` is long gone - let's use `random_int()` instead

2022-03-02 20:05 UTC, Ocramius commented on tests/Integration/Mapping/Object/DateTimeMappingTest.php
> +    private function get_random_timestamp(): int
Perhaps rather than `get`, `makeRandomTimestamp()`?

2022-03-02 20:05 UTC, Ocramius commented on tests/Integration/Mapping/Object/DateTimeMappingTest.php
> +        return mt_rand(1, time());
Not sure whether this needs to be restricted to `time()` as an upper boundary: IMO worth testing also in the far future (year 3000 or so)

2022-03-02 20:21 UTC, Lucian-Olariu commented on tests/Integration/Mapping/Object/DateTimeMappingTest.php
> +use function mt_rand;
Using `random_int()`

2022-03-03 12:00 UTC, romm commented
Hi @Lucian-Olariu, very good contribution, I just cleaned up a bit to ease readability. Thanks a lot! 🙂

2022-03-03 12:02 UTC, merged

2022-03-03 14:09 UTC, Lucian-Olariu commented
Yes wanted to do that but thought more tests will come later and  that is why I declared them in separate variables :+1: